### ISSUE TITLE
Doesn't work if the route uses promises

### ISSUE THREAD

**Issue by thisdotrob** [cmstead/express-route-fake#4]
Nice package, but I can't get it to work when I use promises within the route, e.g.

```
router.get('/path', (req, res) => {
  promiseReturningFunction()
    .then(result => {
      res.send(result);
    };
}
```

when I check res.resData.response it is not updated with the result due to the async call.

Is it possible to make the package handle this?

**Comment by cmstead** [comment]
I think this is beyond the scope of the package. You should consider using a promise mocking or faking solution in order to solve this problem. I'm sorry I don't have a better answer, but this is intended to be little more than a lightweight way to capture the original route function.

I haven't tried this library, but it seems like it might give you the support you need to test your function:

https://github.com/charleshansen/mock-promises
